# Generated by Django 3.2.4 on 2022-08-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200, verbose_name='title')),
                ('description', models.CharField(help_text='Description', max_length=600, verbose_name='description')),
                ('image_url', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='created_at')),
            ],
        ),
    ]
